# Generated by Django 5.2.4 on 2025-07-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('session_description', models.TextField(help_text='Descripción de la sesión o actividad realizada')),
                ('evaluation', models.CharField(choices=[('excellent', 'Excelente Progreso'), ('good', 'Buen Progreso'), ('fair', 'Progreso Regular'), ('poor', 'Necesita Atención'), ('critical', 'Atención Crítica Requerida')], help_text='Evaluación del progreso', max_length=20)),
                ('additional_notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-date_time'],
            },
        ),
    ]
