# Generated by Django 5.2.4 on 2025-08-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Ficha Clínica', 'verbose_name_plural': 'Fichas Clínicas'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='general_notes',
        ),
        migrations.AddField(
            model_name='patient',
            name='abortions_a',
            field=models.PositiveIntegerField(blank=True, help_text='A (Abortos)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='activities_stopped',
            field=models.TextField(blank=True, help_text='Actividad dejada por el problema'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Dirección'),
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Alcohol', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Alergias'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_activities_stopped',
            field=models.TextField(blank=True, help_text='Actividad que dejó por el problema'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_conscious',
            field=models.TextField(blank=True, help_text='¿Es consciente?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_inconsistency',
            field=models.TextField(blank=True, help_text='¿Sufre inconsistencia? ¿Cuándo?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_pad',
            field=models.TextField(blank=True, help_text='¿Apósito?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bristol_scale',
            field=models.PositiveIntegerField(blank=True, help_text='Bristol (1-7)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='child_weight',
            field=models.TextField(blank=True, help_text='Peso del hijo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coloproctologic_exam',
            field=models.TextField(blank=True, help_text='Examen coloproctológico (pendiente)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='complete_evacuation',
            field=models.BooleanField(default=False, help_text='Sensación de evacuación completa'),
        ),
        migrations.AddField(
            model_name='patient',
            name='conscious_urination',
            field=models.TextField(blank=True, help_text='Consciente de cuándo quiere orinar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='constipation',
            field=models.BooleanField(default=False, help_text='Estreñimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consultation_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo de consulta'),
        ),
        migrations.AddField(
            model_name='patient',
            name='containment_capacity',
            field=models.TextField(blank=True, help_text='Capacidad de contención'),
        ),
        migrations.AddField(
            model_name='patient',
            name='daily_frequency',
            field=models.CharField(blank=True, help_text='Frecuencia diaria', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='daily_liquid_consumption',
            field=models.TextField(blank=True, help_text='Consumo líquido diario'),
        ),
        migrations.AddField(
            model_name='patient',
            name='defecation_position',
            field=models.TextField(blank=True, help_text='Posición para hacer caca'),
        ),
        migrations.AddField(
            model_name='patient',
            name='delivery_type',
            field=models.CharField(blank=True, help_text='Partos: normal y/o cesárea', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='diet',
            field=models.TextField(blank=True, help_text='Dieta'),
        ),
        migrations.AddField(
            model_name='patient',
            name='during_pregnancy',
            field=models.TextField(blank=True, help_text='Durante el embarazo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dysuria',
            field=models.BooleanField(default=False, help_text='Disuria'),
        ),
        migrations.AddField(
            model_name='patient',
            name='effort_to_urinate',
            field=models.BooleanField(default=False, help_text='Esfuerzo para orinar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='episiotomies',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Episiotomías', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecal_incontinence',
            field=models.BooleanField(default=False, help_text='Incontinencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gas_incontinence',
            field=models.BooleanField(default=False, help_text='Incontinencia gases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gas_stool_discrimination',
            field=models.BooleanField(default=False, help_text='Discriminación gas de caca'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemorrhoids',
            field=models.BooleanField(default=False, help_text='Hemorroides'),
        ),
        migrations.AddField(
            model_name='patient',
            name='how_daily',
            field=models.TextField(blank=True, help_text='Cómo es por día'),
        ),
        migrations.AddField(
            model_name='patient',
            name='if_field',
            field=models.BooleanField(default=False, help_text='IF'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ig',
            field=models.BooleanField(default=False, help_text='IG'),
        ),
        migrations.AddField(
            model_name='patient',
            name='immediate_need',
            field=models.BooleanField(default=False, help_text='Necesidad inmediata'),
        ),
        migrations.AddField(
            model_name='patient',
            name='incomplete_emptying',
            field=models.BooleanField(default=False, help_text='Sensación vaciamiento incompleto'),
        ),
        migrations.AddField(
            model_name='patient',
            name='incontinence_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AddField(
            model_name='patient',
            name='instrumentation',
            field=models.TextField(blank=True, help_text='Instrumentalización'),
        ),
        migrations.AddField(
            model_name='patient',
            name='intracavitary_exam',
            field=models.TextField(blank=True, help_text='Examen intracavitario (pendiente)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='io',
            field=models.BooleanField(default=False, help_text='IO'),
        ),
        migrations.AddField(
            model_name='patient',
            name='iu_coital',
            field=models.BooleanField(default=False, help_text='IU coital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='iu_posture',
            field=models.BooleanField(default=False, help_text='IU postura'),
        ),
        migrations.AddField(
            model_name='patient',
            name='iu_sensitivity',
            field=models.BooleanField(default=False, help_text='IU sensibilidad'),
        ),
        migrations.AddField(
            model_name='patient',
            name='iue',
            field=models.BooleanField(default=False, help_text='IUE'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ium',
            field=models.BooleanField(default=False, help_text='IUM'),
        ),
        migrations.AddField(
            model_name='patient',
            name='iuu',
            field=models.BooleanField(default=False, help_text='IUU'),
        ),
        migrations.AddField(
            model_name='patient',
            name='latency',
            field=models.BooleanField(default=False, help_text='Latencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='laxatives',
            field=models.BooleanField(default=False, help_text='Laxantes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='losses_p',
            field=models.PositiveIntegerField(blank=True, help_text='P (Pérdidas)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, help_text='Medicamentos actuales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='menopause',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Menopausia', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='menopause_time',
            field=models.CharField(blank=True, help_text='Hace cuánto tiempo', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='muscle_tear',
            field=models.TextField(blank=True, help_text='Desgarro muscular'),
        ),
        migrations.AddField(
            model_name='patient',
            name='musculoskeletal_history',
            field=models.TextField(blank=True, help_text='Antecedentes músculo esquelético quirúrgico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nocturia',
            field=models.BooleanField(default=False, help_text='Nocturia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nocturnal_frequency',
            field=models.CharField(blank=True, help_text='Frecuencia nocturna', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='nocturnal_urgency',
            field=models.BooleanField(default=False, help_text='Urgencia nocturna'),
        ),
        migrations.AddField(
            model_name='patient',
            name='painful_evacuation',
            field=models.BooleanField(default=False, help_text='Evacuación dolorosa'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Teléfono', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity',
            field=models.TextField(blank=True, help_text='Actividad física'),
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_exam',
            field=models.TextField(blank=True, help_text='Examen físico (pendiente)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='plugging_sensation',
            field=models.BooleanField(default=False, help_text='Sensación de tapón'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pollakiuria',
            field=models.BooleanField(default=False, help_text='Polaquiuria'),
        ),
        migrations.AddField(
            model_name='patient',
            name='polyuria',
            field=models.BooleanField(default=False, help_text='Poliuria'),
        ),
        migrations.AddField(
            model_name='patient',
            name='position_frequency',
            field=models.BooleanField(default=False, help_text='Frecuencia de posiciones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='post_pregnancy',
            field=models.TextField(blank=True, help_text='Post embarazo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='postpartum',
            field=models.TextField(blank=True, help_text='Post parto'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancies_g',
            field=models.PositiveIntegerField(blank=True, help_text='G (Gestaciones)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Cirugías previas'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, default='', help_text='Profesión', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='prolapse',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Prolapso', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='prolapse_post_pregnancy',
            field=models.TextField(blank=True, help_text='Prolapso post embarazo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prolapse_type',
            field=models.TextField(blank=True, help_text='¿Cuál prolapso?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='protection_type',
            field=models.TextField(blank=True, help_text='Algún tipo de protección'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rectocele',
            field=models.BooleanField(default=False, help_text='Rectocele'),
        ),
        migrations.AddField(
            model_name='patient',
            name='regular_menstrual_cycle',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Ciclo menstrual regular', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_history',
            field=models.TextField(blank=True, help_text='Historial sexual (pendiente)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='since_when',
            field=models.TextField(blank=True, help_text='Hace cuánto'),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Fuma', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='straining_defecation',
            field=models.BooleanField(default=False, help_text='Puja para defecar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='stream_description',
            field=models.TextField(blank=True, help_text='Descripción de chorro'),
        ),
        migrations.AddField(
            model_name='patient',
            name='terminal_dripping',
            field=models.BooleanField(default=False, help_text='Goteo terminal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urgency',
            field=models.BooleanField(default=False, help_text='Urgencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urination_position',
            field=models.TextField(blank=True, help_text='Micción posición adoptada'),
        ),
        migrations.AddField(
            model_name='patient',
            name='when_occurs_daily',
            field=models.TextField(blank=True, help_text='Cuándo ocurre por día'),
        ),
    ]
