# Generated by Django 5.2.4 on 2025-08-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_options_remove_patient_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='coloproctologic_exam',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intracavitary_exam',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physical_exam',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='adherences',
            field=models.TextField(blank=True, help_text='Adherencias'),
        ),
        migrations.AddField(
            model_name='patient',
            name='anal_canal_closure',
            field=models.BooleanField(default=False, help_text='Cierre canal anal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='anal_canal_relaxation',
            field=models.BooleanField(default=False, help_text='Relajación canal anal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='anal_cutaneous_reflex',
            field=models.BooleanField(default=False, help_text='Reflejo cutáneo anal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='anorectal_opening',
            field=models.BooleanField(default=False, help_text='Apertura ano rectal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blind_rectum',
            field=models.BooleanField(default=False, help_text='Recto ciego'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coloproctologic_consent',
            field=models.BooleanField(default=False, help_text='Consentimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coloproctologic_hemorrhoids',
            field=models.TextField(blank=True, help_text='Hemorroides, dónde'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coloproctologic_scars',
            field=models.TextField(blank=True, help_text='Cicatriz, dónde'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cough_reflex',
            field=models.BooleanField(default=False, help_text='Reflejo tusígeno'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deep_musculature',
            field=models.TextField(blank=True, help_text='Musculatura profunda'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diastasis',
            field=models.TextField(blank=True, help_text='Diastasis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dyspareunia',
            field=models.BooleanField(default=False, help_text='Dispareunia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='eae_contraction',
            field=models.TextField(blank=True, help_text='Contracción EAE'),
        ),
        migrations.AddField(
            model_name='patient',
            name='eae_tonicity_rest',
            field=models.TextField(blank=True, help_text='Tonicidad EAE reposo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecal_incontinence_sexual',
            field=models.BooleanField(default=False, help_text='Incontinencia fecal durante sexo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecal_incontinence_sexual_when',
            field=models.TextField(blank=True, help_text='¿Cuándo?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='impaired_by_incontinence',
            field=models.BooleanField(default=False, help_text='Perjudicado por incontinencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='intracavitary_consent',
            field=models.BooleanField(default=False, help_text='Consentimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='intracavitary_mucosa',
            field=models.TextField(blank=True, help_text='Mucosa'),
        ),
        migrations.AddField(
            model_name='patient',
            name='intracavitary_scars',
            field=models.TextField(blank=True, help_text='Cicatrices'),
        ),
        migrations.AddField(
            model_name='patient',
            name='irritation',
            field=models.BooleanField(default=False, help_text='Irritación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_contraction',
            field=models.TextField(blank=True, help_text='Contracción MEA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_pain_description',
            field=models.TextField(blank=True, help_text='Dolor MEA - Descripción'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_pain_eva',
            field=models.PositiveIntegerField(blank=True, help_text='Dolor MEA - EVA (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_pain_location',
            field=models.TextField(blank=True, help_text='Dolor MEA - Dónde'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_pain_when',
            field=models.TextField(blank=True, help_text='Dolor MEA - Cuándo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_perception',
            field=models.TextField(blank=True, help_text='Percepción MEA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_symmetry_contraction',
            field=models.TextField(blank=True, help_text='Simetría MEA contracción'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_symmetry_rest',
            field=models.TextField(blank=True, help_text='Simetría MEA reposo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_tonicity_rest',
            field=models.TextField(blank=True, help_text='Tonicidad MEA reposo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mea_voluntary_relaxation',
            field=models.TextField(blank=True, help_text='Relajación voluntaria MEA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nlp_tone_contraction',
            field=models.TextField(blank=True, help_text='NLP Tono - Contracción'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nlp_tone_pain',
            field=models.TextField(blank=True, help_text='NLP Tono - Dolor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nlp_tone_push',
            field=models.TextField(blank=True, help_text='NLP Tono - Pujo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nlp_tone_relaxation',
            field=models.TextField(blank=True, help_text='NLP Tono - Relajación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='orgasm',
            field=models.BooleanField(default=False, help_text='Orgasmo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxford_anorectal_angle',
            field=models.TextField(blank=True, help_text='Ángulo ano rectal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxford_force',
            field=models.TextField(blank=True, help_text='Fuerza (Oxford)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='push_exam',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterado', 'Alterado')], help_text='Pujo', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='rectal_torso_synchronization',
            field=models.BooleanField(default=False, help_text='Sincronización torso rectal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='resistance',
            field=models.TextField(blank=True, help_text='Resistencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rest_tone',
            field=models.TextField(blank=True, help_text='Tono en reposo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='scars',
            field=models.TextField(blank=True, help_text='Cicatrices'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_desire',
            field=models.BooleanField(default=False, help_text='Deseo sexual'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_excitement',
            field=models.BooleanField(default=False, help_text='Excitación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexually_active',
            field=models.BooleanField(default=False, help_text='Activo sexualmente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexually_active_when',
            field=models.TextField(blank=True, help_text='¿Cuándo?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='skin_coloration',
            field=models.TextField(blank=True, help_text='Coloración de la piel'),
        ),
        migrations.AddField(
            model_name='patient',
            name='stool_remains',
            field=models.BooleanField(default=False, help_text='Resto de deposiciones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='superficial_muscle',
            field=models.TextField(blank=True, help_text='Muscular superficial'),
        ),
        migrations.AddField(
            model_name='patient',
            name='transverse_urethral_tone',
            field=models.TextField(blank=True, help_text='Tono del transverso uretral'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urethral_movement',
            field=models.TextField(blank=True, help_text='Movimiento uretral'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urge_to_urinate_during_sex',
            field=models.BooleanField(default=False, help_text='Siente deseo de orinar durante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urinary_incontinence_sexual',
            field=models.BooleanField(default=False, help_text='Incontinencia orina durante sexo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urinary_incontinence_sexual_when',
            field=models.TextField(blank=True, help_text='¿Cuándo?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaginal_dryness',
            field=models.BooleanField(default=False, help_text='Resequedad'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vulvo_cavernous_reflex',
            field=models.BooleanField(default=False, help_text='Reflejo vulvo cavernoso'),
        ),
    ]
