# Generated by Django 5.2.4 on 2025-08-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_patient_coloproctologic_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blind_rectum',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nlp_tone_contraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nlp_tone_pain',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nlp_tone_push',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nlp_tone_relaxation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rectal_torso_synchronization',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexually_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexually_active_when',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='superficial_muscle',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='transverse_urethral_tone',
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_function_other',
            field=models.TextField(blank=True, help_text='Otros - Funcionamiento intestinal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coloproctologic_exam_other',
            field=models.TextField(blank=True, help_text='Otros - Examen coloproctológico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gynecological_other',
            field=models.TextField(blank=True, help_text='Otros - Antecedentes ginecológicos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='intracavitary_exam_other',
            field=models.TextField(blank=True, help_text='Otros - Examen intracavitario'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(default=False, help_text='¿Está embarazada?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lifestyle_other',
            field=models.TextField(blank=True, help_text='Otros - Hábitos de vida'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ncp_tone_contraction',
            field=models.TextField(blank=True, help_text='NCP Tono - Contracción'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ncp_tone_pain',
            field=models.TextField(blank=True, help_text='NCP Tono - Dolor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ncp_tone_push',
            field=models.TextField(blank=True, help_text='NCP Tono - Pujo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ncp_tone_relaxation',
            field=models.TextField(blank=True, help_text='NCP Tono - Relajación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxford_notes',
            field=models.TextField(blank=True, help_text='Oxford - Notas'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_data_other',
            field=models.TextField(blank=True, help_text='Otros - Datos del paciente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_exam_other',
            field=models.TextField(blank=True, help_text='Otros - Examen físico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio del embarazo', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_week_day',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Día de la semana para contar semanas', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='rectocele_exam',
            field=models.BooleanField(default=False, help_text='Recto cele'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_history_other',
            field=models.TextField(blank=True, help_text='Otros - Historial sexual'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_status',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('virgen', 'Virgen')], help_text='Estado sexual', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='superficial_musculature',
            field=models.TextField(blank=True, help_text='Musculatura superficial'),
        ),
        migrations.AddField(
            model_name='patient',
            name='thoracic_rectal_synchronization',
            field=models.BooleanField(default=False, help_text='Sincronización toraco rectal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='transverse_abdominal_tone',
            field=models.TextField(blank=True, help_text='Tono del transverso abdominal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='urinary_function_other',
            field=models.TextField(blank=True, help_text='Otros - Función urinaria'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anal_cutaneous_reflex',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo cutáneo anal', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cough_reflex',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo tusígeno', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='position_frequency',
            field=models.TextField(blank=True, help_text='Frecuencia de posiciones'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vulvo_cavernous_reflex',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo vulvo cavernoso', max_length=10),
        ),
    ]
