# Generated by Django 5.2.4 on 2025-08-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_patient_blind_rectum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pregnancy_start_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_registration_date',
            field=models.DateField(blank=True, help_text='Fecha cuando se registraron las semanas', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_weeks_at_registration',
            field=models.PositiveIntegerField(blank=True, help_text='Semanas de embarazo al momento del registro', null=True),
        ),
    ]
