# Generated by Django 5.2.4 on 2025-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_patient_pregnancy_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bowel_function_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='coloproctologic_exam_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gynecological_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='intracavitary_exam_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lifestyle_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physical_exam_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexual_history_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='urinary_function_other',
            field=models.TextField(blank=True, help_text='Otros'),
        ),
    ]
