# Generated by Django 5.2.4 on 2025-08-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patient_bowel_function_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_c_cocontraction',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='C - Co-contraction (Co-contracción)', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_e_endurance',
            field=models.PositiveIntegerField(blank=True, help_text='E - Endurance (Resistencia)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_e_every',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='E - Every contraction (Cada contracción)', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_f_fast',
            field=models.PositiveIntegerField(blank=True, help_text='F - Fast contractions (Contracciones rápidas)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_p_power',
            field=models.PositiveIntegerField(blank=True, help_text='P - Power (Fuerza)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_r_repetitions',
            field=models.PositiveIntegerField(blank=True, help_text='R - Repetitions (Repeticiones)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='perfect_t_timing',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='T - Timing (Coordinación)', max_length=10),
        ),
    ]
