# Generated by Django 5.2.4 on 2025-08-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_update_appointment_perfect_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='balloon_expulsion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Expulsión del balón', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='balloon_first_desire_volume',
            field=models.TextField(blank=True, help_text='Volumen Primer deseo: 50 - 60 ml'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='balloon_max_tolerable_capacity',
            field=models.TextField(blank=True, help_text='Capacidad máxima tolerable: máximo tolerable 200-240 ml'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='balloon_normal_desire_volume',
            field=models.TextField(blank=True, help_text='Volumen Deseo normal constante: sin acomodación 90 - 120ml'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='balloon_rectal_sensation',
            field=models.TextField(blank=True, help_text='Sensación rectal consciente: 10 - 30 ml'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='balloon_rectoanal_reflex',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo rectoanal estriado', max_length=10),
        ),
    ]
