# Generated by Django 5.2.4 on 2025-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_balloon_test_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alta',
            field=models.BooleanField(default=False, help_text='Indica si el paciente fue dado de alta y se cerró su ciclo clínico.'),
        ),
    ]
