# Generated by Django 5.2.4 on 2025-08-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patient_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tasks',
            field=models.TextField(blank=True, help_text='Tareas o indicaciones para seguimiento'),
        ),
    ]
