# Generated by Django 5.2.4 on 2025-08-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_banquito',
            field=models.BooleanField(default=False, help_text='Aprendió uso de banquito'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_contraccion_pelvico',
            field=models.BooleanField(default=False, help_text='Aprendió contracción piso pélvico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_anatomia',
            field=models.BooleanField(default=False, help_text='Aprendió anatomía'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_intervencion',
            field=models.BooleanField(default=False, help_text='Aprendió intervención obstétrica'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_masaje_perineal',
            field=models.BooleanField(default=False, help_text='Aprendió masaje perineal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_movimientos',
            field=models.BooleanField(default=False, help_text='Aprendió movimientos cardinales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_oms',
            field=models.BooleanField(default=False, help_text='Aprendió OMS'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_otros',
            field=models.TextField(blank=True, help_text='Otros aprendizajes embarazo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_posicion_expulsion',
            field=models.BooleanField(default=False, help_text='Aprendió posición expulsión'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_posicion_trabajo',
            field=models.BooleanField(default=False, help_text='Aprendió posición trabajo parto'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_pujo',
            field=models.BooleanField(default=False, help_text='Aprendió pujo embarazo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_respiraciones',
            field=models.BooleanField(default=False, help_text='Aprendió respiraciones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_emb_tecnicas_dolor',
            field=models.BooleanField(default=False, help_text='Aprendió técnicas de dolor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_otros',
            field=models.TextField(blank=True, help_text='Otros aprendizajes generales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_preapretar',
            field=models.BooleanField(default=False, help_text='Aprendió preapretar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_pujo_caca',
            field=models.BooleanField(default=False, help_text='Aprendió pujo caca'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_respiracion_pelvico',
            field=models.BooleanField(default=False, help_text='Aprendió coordinación respiración contracción piso pélvico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aprendizaje_transverso',
            field=models.BooleanField(default=False, help_text='Aprendió activación transverso abdominal'),
        ),
    ]
