# Generated by Django 5.2.4 on 2025-09-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patient_aprendizaje_banquito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='activities_stopped',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='adherences',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='anal_canal_closure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='anal_canal_relaxation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='anal_cutaneous_reflex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='anorectal_opening',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_banquito',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_contraccion_pelvico',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_anatomia',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_intervencion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_masaje_perineal',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_movimientos',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_oms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_otros',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_posicion_expulsion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_posicion_trabajo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_pujo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_respiraciones',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_emb_tecnicas_dolor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_otros',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_preapretar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_pujo_caca',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_respiracion_pelvico',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aprendizaje_transverso',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bowel_activities_stopped',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bowel_conscious',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bowel_function_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bowel_inconsistency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bowel_pad',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bristol_scale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coloproctologic_consent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coloproctologic_exam_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coloproctologic_hemorrhoids',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coloproctologic_scars',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='complete_evacuation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='conscious_urination',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='constipation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consultation_reason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='containment_capacity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cough_reflex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='daily_frequency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='daily_liquid_consumption',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deep_musculature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='defecation_position',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diastasis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='during_pregnancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dyspareunia',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dysuria',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eae_contraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eae_tonicity_rest',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='effort_to_urinate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecal_incontinence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecal_incontinence_sexual',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecal_incontinence_sexual_when',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gas_incontinence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gas_stool_discrimination',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hemorrhoids',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='how_daily',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='immediate_need',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='impaired_by_incontinence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='incomplete_emptying',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='incontinence_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intracavitary_consent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intracavitary_exam_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intracavitary_mucosa',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intracavitary_scars',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='irritation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='iu_coital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='iu_posture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='iu_sensitivity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='iue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ium',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='iuu',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='laxatives',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lifestyle_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_contraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_pain_description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_pain_eva',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_pain_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_pain_when',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_perception',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_symmetry_contraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_symmetry_rest',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_tonicity_rest',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mea_voluntary_relaxation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ncp_tone_contraction',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ncp_tone_pain',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ncp_tone_push',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ncp_tone_relaxation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nocturia',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nocturnal_frequency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nocturnal_urgency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='orgasm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxford_anorectal_angle',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxford_force',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxford_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='painful_evacuation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_data_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physical_activity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physical_exam_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='plugging_sensation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pollakiuria',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='polyuria',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='position_frequency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='post_pregnancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prolapse_post_pregnancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='protection_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='push_exam',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rectocele',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rectocele_exam',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='resistance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rest_tone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='scars',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_desire',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_excitement',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_history_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='since_when',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='skin_coloration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stool_remains',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='straining_defecation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stream_description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='superficial_musculature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='terminal_dripping',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='thoracic_rectal_synchronization',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='transverse_abdominal_tone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urethral_movement',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urge_to_urinate_during_sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urinary_function_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urinary_incontinence_sexual',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urinary_incontinence_sexual_when',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='urination_position',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vaginal_dryness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vulvo_cavernous_reflex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='when_occurs_daily',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_postpartum',
            field=models.BooleanField(default=False, help_text='¿Está en postparto?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='postpartum_registration_date',
            field=models.DateField(blank=True, help_text='Fecha cuando se registraron las semanas postparto', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postpartum_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio del postparto', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postpartum_week_day',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Día de la semana para contar semanas postparto', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='postpartum_weeks_at_registration',
            field=models.PositiveIntegerField(blank=True, help_text='Semanas de postparto al momento del registro', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='musculoskeletal_history',
            field=models.TextField(blank=True, help_text='Antecedentes músculo esquelético'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pregnancy_weeks_at_registration',
            field=models.PositiveIntegerField(blank=True, help_text='Semanas de embarazo al momento del registro (máximo 42)', null=True),
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_reason', models.TextField(blank=True, default='', help_text='Motivo de consulta')),
                ('aprendizaje_pujo_caca', models.BooleanField(default=False, help_text='Aprendió pujo caca')),
                ('aprendizaje_banquito', models.BooleanField(default=False, help_text='Aprendió uso de banquito')),
                ('aprendizaje_transverso', models.BooleanField(default=False, help_text='Aprendió activación transverso abdominal')),
                ('aprendizaje_respiracion_pelvico', models.BooleanField(default=False, help_text='Aprendió coordinación respiración contracción piso pélvico')),
                ('aprendizaje_contraccion_pelvico', models.BooleanField(default=False, help_text='Aprendió contracción piso pélvico')),
                ('aprendizaje_preapretar', models.BooleanField(default=False, help_text='Aprendió preapretar')),
                ('aprendizaje_otros', models.TextField(blank=True, help_text='Otros aprendizajes generales')),
                ('aprendizaje_emb_oms', models.BooleanField(default=False, help_text='Aprendió OMS')),
                ('aprendizaje_emb_anatomia', models.BooleanField(default=False, help_text='Aprendió anatomía')),
                ('aprendizaje_emb_movimientos', models.BooleanField(default=False, help_text='Aprendió movimientos cardinales')),
                ('aprendizaje_emb_posicion_trabajo', models.BooleanField(default=False, help_text='Aprendió posición trabajo parto')),
                ('aprendizaje_emb_posicion_expulsion', models.BooleanField(default=False, help_text='Aprendió posición expulsión')),
                ('aprendizaje_emb_intervencion', models.BooleanField(default=False, help_text='Aprendió intervención obstétrica')),
                ('aprendizaje_emb_masaje_perineal', models.BooleanField(default=False, help_text='Aprendió masaje perineal')),
                ('aprendizaje_emb_respiraciones', models.BooleanField(default=False, help_text='Aprendió respiraciones')),
                ('aprendizaje_emb_pujo', models.BooleanField(default=False, help_text='Aprendió pujo embarazo')),
                ('aprendizaje_emb_tecnicas_dolor', models.BooleanField(default=False, help_text='Aprendió técnicas de dolor')),
                ('aprendizaje_emb_otros', models.TextField(blank=True, help_text='Otros aprendizajes embarazo')),
                ('smoking', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Fuma', max_length=10)),
                ('alcohol', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Alcohol', max_length=10)),
                ('physical_activity', models.TextField(blank=True, help_text='Actividad física')),
                ('diet', models.TextField(blank=True, help_text='Dieta')),
                ('daily_liquid_consumption', models.TextField(blank=True, help_text='Consumo líquido diario')),
                ('lifestyle_other', models.TextField(blank=True, help_text='Otros')),
                ('daily_frequency', models.CharField(blank=True, help_text='Frecuencia diaria', max_length=50)),
                ('nocturnal_frequency', models.CharField(blank=True, help_text='Frecuencia nocturna', max_length=50)),
                ('pollakiuria', models.BooleanField(default=False, help_text='Polaquiuria')),
                ('nocturia', models.BooleanField(default=False, help_text='Nocturia')),
                ('urgency', models.BooleanField(default=False, help_text='Urgencia')),
                ('polyuria', models.BooleanField(default=False, help_text='Poliuria')),
                ('dysuria', models.BooleanField(default=False, help_text='Disuria')),
                ('latency', models.BooleanField(default=False, help_text='Latencia')),
                ('effort_to_urinate', models.BooleanField(default=False, help_text='Esfuerzo para orinar')),
                ('incomplete_emptying', models.BooleanField(default=False, help_text='Sensación vaciamiento incompleto')),
                ('immediate_need', models.BooleanField(default=False, help_text='Necesidad inmediata')),
                ('terminal_dripping', models.BooleanField(default=False, help_text='Goteo terminal')),
                ('nocturnal_urgency', models.BooleanField(default=False, help_text='Urgencia nocturna')),
                ('urination_position', models.TextField(blank=True, help_text='Micción posición adoptada')),
                ('stream_description', models.TextField(blank=True, help_text='Descripción de chorro')),
                ('urinary_function_other', models.TextField(blank=True, help_text='Otros')),
                ('iue', models.BooleanField(default=False, help_text='IUE')),
                ('iuu', models.BooleanField(default=False, help_text='IUU')),
                ('ium', models.BooleanField(default=False, help_text='IUM')),
                ('iu_posture', models.BooleanField(default=False, help_text='IU postura')),
                ('iu_sensitivity', models.BooleanField(default=False, help_text='IU sensibilidad')),
                ('iu_coital', models.BooleanField(default=False, help_text='IU coital')),
                ('incontinence_other', models.TextField(blank=True, help_text='Otros')),
                ('when_occurs_daily', models.TextField(blank=True, help_text='Cuándo ocurre por día')),
                ('how_daily', models.TextField(blank=True, help_text='Cómo es por día')),
                ('since_when', models.TextField(blank=True, help_text='Hace cuánto')),
                ('during_pregnancy', models.TextField(blank=True, help_text='Durante el embarazo')),
                ('post_pregnancy', models.TextField(blank=True, help_text='Post embarazo')),
                ('prolapse_post_pregnancy', models.TextField(blank=True, help_text='Prolapso post embarazo')),
                ('conscious_urination', models.TextField(blank=True, help_text='Consciente de cuándo quiere orinar')),
                ('containment_capacity', models.TextField(blank=True, help_text='Capacidad de contención')),
                ('protection_type', models.TextField(blank=True, help_text='Algún tipo de protección')),
                ('activities_stopped', models.TextField(blank=True, help_text='Actividad dejada por el problema')),
                ('constipation', models.BooleanField(default=False, help_text='Estreñimiento')),
                ('fecal_incontinence', models.BooleanField(default=False, help_text='Incontinencia')),
                ('gas_incontinence', models.BooleanField(default=False, help_text='Incontinencia gases')),
                ('hemorrhoids', models.BooleanField(default=False, help_text='Hemorroides')),
                ('rectocele', models.BooleanField(default=False, help_text='Rectocele')),
                ('gas_stool_discrimination', models.BooleanField(default=False, help_text='Discriminación gas de caca')),
                ('painful_evacuation', models.BooleanField(default=False, help_text='Evacuación dolorosa')),
                ('straining_defecation', models.BooleanField(default=False, help_text='Puja para defecar')),
                ('complete_evacuation', models.BooleanField(default=False, help_text='Sensación de evacuación completa')),
                ('laxatives', models.BooleanField(default=False, help_text='Laxantes')),
                ('plugging_sensation', models.BooleanField(default=False, help_text='Sensación de tapón')),
                ('defecation_position', models.TextField(blank=True, help_text='Posición para hacer caca')),
                ('bristol_scale', models.PositiveIntegerField(blank=True, help_text='Bristol (1-7)', null=True)),
                ('position_frequency', models.TextField(blank=True, help_text='Frecuencia de posiciones')),
                ('bowel_inconsistency', models.TextField(blank=True, help_text='¿Sufre inconsistencia? ¿Cuándo?')),
                ('bowel_conscious', models.TextField(blank=True, help_text='¿Es consciente?')),
                ('bowel_pad', models.TextField(blank=True, help_text='¿Apósito?')),
                ('bowel_activities_stopped', models.TextField(blank=True, help_text='Actividad que dejó por el problema')),
                ('bowel_function_other', models.TextField(blank=True, help_text='Otros')),
                ('sexual_status', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('virgen', 'Virgen')], help_text='Estado sexual', max_length=10)),
                ('urinary_incontinence_sexual', models.BooleanField(default=False, help_text='Incontinencia orina durante sexo')),
                ('urinary_incontinence_sexual_when', models.TextField(blank=True, help_text='¿Cuándo?')),
                ('fecal_incontinence_sexual', models.BooleanField(default=False, help_text='Incontinencia fecal durante sexo')),
                ('fecal_incontinence_sexual_when', models.TextField(blank=True, help_text='¿Cuándo?')),
                ('sexual_desire', models.BooleanField(default=False, help_text='Deseo sexual')),
                ('sexual_excitement', models.BooleanField(default=False, help_text='Excitación')),
                ('orgasm', models.BooleanField(default=False, help_text='Orgasmo')),
                ('dyspareunia', models.BooleanField(default=False, help_text='Dispareunia')),
                ('urge_to_urinate_during_sex', models.BooleanField(default=False, help_text='Siente deseo de orinar durante')),
                ('vaginal_dryness', models.BooleanField(default=False, help_text='Resequedad')),
                ('impaired_by_incontinence', models.BooleanField(default=False, help_text='Perjudicado por incontinencia')),
                ('sexual_history_other', models.TextField(blank=True, help_text='Otros')),
                ('diastasis', models.TextField(blank=True, help_text='Diastasis')),
                ('scars', models.TextField(blank=True, help_text='Cicatrices')),
                ('adherences', models.TextField(blank=True, help_text='Adherencias')),
                ('skin_coloration', models.TextField(blank=True, help_text='Coloración de la piel')),
                ('push_exam', models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterado', 'Alterado')], help_text='Pujo', max_length=20)),
                ('ncp_tone_contraction', models.TextField(blank=True, help_text='NCP Tono - Contracción')),
                ('ncp_tone_relaxation', models.TextField(blank=True, help_text='NCP Tono - Relajación')),
                ('ncp_tone_push', models.TextField(blank=True, help_text='NCP Tono - Pujo')),
                ('ncp_tone_pain', models.TextField(blank=True, help_text='NCP Tono - Dolor')),
                ('anal_cutaneous_reflex', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo cutáneo anal', max_length=10)),
                ('vulvo_cavernous_reflex', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo vulvo cavernoso', max_length=10)),
                ('cough_reflex', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], help_text='Reflejo tusígeno', max_length=10)),
                ('physical_exam_other', models.TextField(blank=True, help_text='Otros')),
                ('intracavitary_consent', models.BooleanField(default=False, help_text='Consentimiento')),
                ('intracavitary_scars', models.TextField(blank=True, help_text='Cicatrices')),
                ('intracavitary_mucosa', models.TextField(blank=True, help_text='Mucosa')),
                ('mea_tonicity_rest', models.TextField(blank=True, help_text='Tonicidad MEA reposo')),
                ('mea_perception', models.TextField(blank=True, help_text='Percepción MEA')),
                ('mea_contraction', models.TextField(blank=True, help_text='Contracción MEA')),
                ('mea_symmetry_rest', models.TextField(blank=True, help_text='Simetría MEA reposo')),
                ('mea_symmetry_contraction', models.TextField(blank=True, help_text='Simetría MEA contracción')),
                ('mea_voluntary_relaxation', models.TextField(blank=True, help_text='Relajación voluntaria MEA')),
                ('mea_pain_eva', models.PositiveIntegerField(blank=True, help_text='Dolor MEA - EVA (0-10)', null=True)),
                ('mea_pain_location', models.TextField(blank=True, help_text='Dolor MEA - Dónde')),
                ('mea_pain_when', models.TextField(blank=True, help_text='Dolor MEA - Cuándo')),
                ('mea_pain_description', models.TextField(blank=True, help_text='Dolor MEA - Descripción')),
                ('urethral_movement', models.TextField(blank=True, help_text='Movimiento uretral')),
                ('transverse_abdominal_tone', models.TextField(blank=True, help_text='Tono del transverso abdominal')),
                ('oxford_force', models.TextField(blank=True, help_text='Fuerza (Oxford)')),
                ('superficial_musculature', models.TextField(blank=True, help_text='Musculatura superficial')),
                ('deep_musculature', models.TextField(blank=True, help_text='Musculatura profunda')),
                ('intracavitary_exam_other', models.TextField(blank=True, help_text='Otros')),
                ('coloproctologic_consent', models.BooleanField(default=False, help_text='Consentimiento')),
                ('anal_canal_closure', models.BooleanField(default=False, help_text='Cierre canal anal')),
                ('irritation', models.BooleanField(default=False, help_text='Irritación')),
                ('stool_remains', models.BooleanField(default=False, help_text='Resto de deposiciones')),
                ('rectocele_exam', models.BooleanField(default=False, help_text='Recto cele')),
                ('coloproctologic_scars', models.TextField(blank=True, help_text='Cicatriz, dónde')),
                ('coloproctologic_hemorrhoids', models.TextField(blank=True, help_text='Hemorroides, dónde')),
                ('rest_tone', models.TextField(blank=True, help_text='Tono en reposo')),
                ('resistance', models.TextField(blank=True, help_text='Resistencia')),
                ('eae_tonicity_rest', models.TextField(blank=True, help_text='Tonicidad EAE reposo')),
                ('eae_contraction', models.TextField(blank=True, help_text='Contracción EAE')),
                ('oxford_anorectal_angle', models.TextField(blank=True, help_text='Ángulo ano rectal')),
                ('oxford_notes', models.TextField(blank=True, help_text='Oxford - Notas')),
                ('anorectal_opening', models.BooleanField(default=False, help_text='Apertura ano rectal')),
                ('thoracic_rectal_synchronization', models.BooleanField(default=False, help_text='Sincronización toraco rectal')),
                ('anal_canal_relaxation', models.BooleanField(default=False, help_text='Relajación canal anal')),
                ('coloproctologic_exam_other', models.TextField(blank=True, help_text='Otros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Paciente', on_delete=django.db.models.deletion.CASCADE, related_name='fichas_clinicas', to='core.patient')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
