# Generated by Django 5.2.4 on 2025-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_data_other',
            field=models.TextField(blank=True, help_text='Otros datos del paciente'),
        ),
    ]
