# Generated by Django 5.2.4 on 2025-09-05 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_patient_patient_data_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaclinica',
            name='daily_frequency',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='nocturnal_frequency',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='daily_frequency_final',
            field=models.CharField(blank=True, help_text='Frecuencia diaria final', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='daily_frequency_initial',
            field=models.CharField(blank=True, help_text='Frecuencia diaria inicial', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='nocturnal_frequency_final',
            field=models.CharField(blank=True, help_text='Frecuencia nocturna final', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='nocturnal_frequency_initial',
            field=models.CharField(blank=True, help_text='Frecuencia nocturna inicial', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=datetime.date(1990, 1, 11), help_text='Fecha de nacimiento del paciente'),
            preserve_default=False,
        ),
    ]
