# Generated by Django 5.2.4 on 2025-09-09 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_fichaclinica_daily_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaclinica',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Ficha Clínica', 'verbose_name_plural': 'Fichas Clínicas'},
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de la ficha clínica'),
        ),
    ]
